# Pandas Functions

In [1]:
import pandas as pd

In [4]:
csv_1 = pd.read_csv("sample.csv",nrows = 30)
csv_1

    Number                                           Footnote
0        1  Sector and published industry breakdowns accor...
1        2  In 2019 the R&D Survey was conducted only for ...
2        3  Results for this category should be treated wi...
3        4  Includes a wide range of ANZSIC industry codes...
4        5  Based on Rolling Mean employment. See Datainfo...
5        6  Only collected from the business sector. Not c...
6        7  Only collected from the business sector and go...
7        8  Only collected from the business sector and hi...
8        9  Only collected from the government and higher ...
9       10  Only collected from the  higher education sect...
10      11  Only collected from the the Crown Research Ins...
11      12  Dollar figures exclude GST and are rounded to ...
12      13  Underlying counts of businesses are random rou...
13      14  Underlying counts of employees are rounded usi...
14      15  Respondents are asked to allocate to each of t...
15      16  Includes 'defence' and 'other' research purposes.
16      17  Research intended to benefit the sectors of Pl...
17      18  Research intended to benefit the sectors of En...
18      19  Research intended to benefit the sectors of He...
19      20  Research intended to benefit the sectors of Ec...
20      21    Includes New Zealand local government agencies.
21      22  Basic research is carried out to advance knowl...
22      23  Pure basic research is research to pursue new ...
23      24  Targeted basic research is research to produce...
24      25  Applied research is investigation undertaken t...
25      26  Experimental research is systematic work under...
26      27  Businesses were asked to indicate one main rea...
27      28  Some categories or groups may not equal the to...
28      29       Excludes licensing of intellectual property.
29      30                              Excludes subsidaries.

In [5]:
# to know about the indexing

csv_1.index

RangeIndex(start=0, stop=30, step=1)

In [6]:
# info about the columns

csv_1.columns

Index(['Number', 'Footnote'], dtype='object')

In [9]:
csv_1.describe() # describes the whole data

          Number
count  30.000000
mean   15.500000
std     8.803408
min     1.000000
25%     8.250000
50%    15.500000
75%    22.750000
max    30.000000

In [10]:
 csv_1.head(1)
    
# shows data from heading --------

   Number                                           Footnote
0       1  Sector and published industry breakdowns accor...

In [11]:
csv_1.head(5)

   Number                                           Footnote
0       1  Sector and published industry breakdowns accor...
1       2  In 2019 the R&D Survey was conducted only for ...
2       3  Results for this category should be treated wi...
3       4  Includes a wide range of ANZSIC industry codes...
4       5  Based on Rolling Mean employment. See Datainfo...

In [12]:
# ---------shows data from footer--------------

csv_1.tail(2)

    Number                                      Footnote
28      29  Excludes licensing of intellectual property.
29      30                         Excludes subsidaries.

#### To get data of particular range

In [13]:
csv_1[:5] ## shows data from 0 to 5th(index=4)

   Number                                           Footnote
0       1  Sector and published industry breakdowns accor...
1       2  In 2019 the R&D Survey was conducted only for ...
2       3  Results for this category should be treated wi...
3       4  Includes a wide range of ANZSIC industry codes...
4       5  Based on Rolling Mean employment. See Datainfo...

In [14]:
csv_1[4:11]  # shows data from range 4 to 10

    Number                                           Footnote
4        5  Based on Rolling Mean employment. See Datainfo...
5        6  Only collected from the business sector. Not c...
6        7  Only collected from the business sector and go...
7        8  Only collected from the business sector and hi...
8        9  Only collected from the government and higher ...
9       10  Only collected from the  higher education sect...
10      11  Only collected from the the Crown Research Ins...

In [16]:
print(type(csv_1))

# Hence the data type is shown in DataFrame type ..............

<class 'pandas.core.frame.DataFrame'>

In [17]:
# change the datatype to ARRAY 

csv_1.index.array

<PandasArray>
[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18,
 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29]
Length: 30, dtype: int64

#### convert into NumPy array

In [19]:
csv_1.to_numpy()

array([[1,
        "Sector and published industry breakdowns accord with the Organisation for Economic Co-operation and Development's (OECD) recommendations for international comparability. See DataInfo+ section on Published sector and industry breakdowns for more information."],
       [2,
        'In 2019 the R&D Survey was conducted only for the business sector. Every two years, all three sectors of Business,  Government and Higher Education are surveyed.'],
       [3,
        'Results for this category should be treated with caution due to the small numbers of businesses in this category.'],
       [4,
        'Includes a wide range of ANZSIC industry codes. See DataInfo+ section on Published sector and industry breakdowns for more information.'],
       [5,
        'Based on Rolling Mean employment. See Datainfo+ for RME definitions.'],
       [6,
        'Only collected from the business sector. Not collected from the government or higher education sectors.'],
       [7,
        'Only collected from the business sector and government sectors. Not collected from the higher education sector.'],
       [8,
        'Only collected from the business sector and higher education sectors. Not collected from the government sector.'],
       [9,
        'Only collected from the government and higher education sectors. Not collected from the business sector.'],
       [10,
        'Only collected from the  higher education sector. Not collected from the business or government sectors.'],
       [11,
        "Only collected from the the Crown Research Institutes (CRI's) portion of the government sector, and the higher education sector. Not collected from the business sector, or other entities (eg non-CRI's) in the government sector."],
       [12,
        'Dollar figures exclude GST and are rounded to the nearest million.'],
       [13,
        'Underlying counts of businesses are random rounded to base 3.'],
       [14,
        'Underlying counts of employees are rounded using graduated random rounding to base 3.'],
       [15,
        'Respondents are asked to allocate to each of the relevant sectors, a proportion of their total R&D expenditure. This relates to the sector that that will ultimately benefit from the results, not the nature of the R&D itself.'],
       [16, "Includes 'defence' and 'other' research purposes."],
       [17,
        'Research intended to benefit the sectors of Plant production and plant primary products, Animal production and animal primary products, or Mineral resources (excluding energy). Full defintions available from the survey questionnaires on DataInfo+'],
       [18,
        'Research intended to benefit the sectors of Energy, Manufacturing, Construction, Transport, Information and communication services, or Commercial services and tourism. Full defintions available from the survey questionnaires on DataInfo+'],
       [19,
        'Research intended to benefit the sectors of Health, Education and training, Law, politics, community services or Cultural understanding. Full defintions available from the survey questionnaires on DataInfo+'],
       [20,
        'Research intended to benefit the sectors of Econmic frameworks, Environment, Defence, other or knowledge. Full defintions available from the survey questionnaires on DataInfo+'],
       [21, 'Includes New Zealand local government agencies.'],
       [22,
        'Basic research is carried out to advance knowledge, without seeking long-term economic or social benefits or making any effort to apply the results to sectors responsible for their application.'],
       [23,
        'Pure basic research is research to pursue new knowledge without any particular application in view. '],
       [24,
        'Targeted basic research is research to produce a broad base of new knowledge likely to underpin solutions to current or future applications. '],
       [25,
        'Applied research is investigation undertaken to acquire new knowledge. It is directed primarily towards a specific practical aim or objective.'],
       [26,
        'Experimental research is systematic work undertaken using existing knowledge for the purpose of creating new or improved materials, products, and/or services.'],
       [27,
        'Businesses were asked to indicate one main reason for carrying out or funding R&D. However, some businesses indicated more than one reason. Therefore some percentages may sum to more than 100%. Percentages are of total businesses in each industry group carrying out R&D.'],
       [28,
        'Some categories or groups may not equal the total, as some units can not be imputed or corrected, due to lack of appropriate information.'],
       [29, 'Excludes licensing of intellectual property.'],
       [30, 'Excludes subsidaries.']], dtype=object)

In [22]:
# alternative to convert NumPy array --------

import numpy as np
a = np.array(csv_1)
a

array([[1,
        "Sector and published industry breakdowns accord with the Organisation for Economic Co-operation and Development's (OECD) recommendations for international comparability. See DataInfo+ section on Published sector and industry breakdowns for more information."],
       [2,
        'In 2019 the R&D Survey was conducted only for the business sector. Every two years, all three sectors of Business,  Government and Higher Education are surveyed.'],
       [3,
        'Results for this category should be treated with caution due to the small numbers of businesses in this category.'],
       [4,
        'Includes a wide range of ANZSIC industry codes. See DataInfo+ section on Published sector and industry breakdowns for more information.'],
       [5,
        'Based on Rolling Mean employment. See Datainfo+ for RME definitions.'],
       [6,
        'Only collected from the business sector. Not collected from the government or higher education sectors.'],
       [7,
        'Only collected from the business sector and government sectors. Not collected from the higher education sector.'],
       [8,
        'Only collected from the business sector and higher education sectors. Not collected from the government sector.'],
       [9,
        'Only collected from the government and higher education sectors. Not collected from the business sector.'],
       [10,
        'Only collected from the  higher education sector. Not collected from the business or government sectors.'],
       [11,
        "Only collected from the the Crown Research Institutes (CRI's) portion of the government sector, and the higher education sector. Not collected from the business sector, or other entities (eg non-CRI's) in the government sector."],
       [12,
        'Dollar figures exclude GST and are rounded to the nearest million.'],
       [13,
        'Underlying counts of businesses are random rounded to base 3.'],
       [14,
        'Underlying counts of employees are rounded using graduated random rounding to base 3.'],
       [15,
        'Respondents are asked to allocate to each of the relevant sectors, a proportion of their total R&D expenditure. This relates to the sector that that will ultimately benefit from the results, not the nature of the R&D itself.'],
       [16, "Includes 'defence' and 'other' research purposes."],
       [17,
        'Research intended to benefit the sectors of Plant production and plant primary products, Animal production and animal primary products, or Mineral resources (excluding energy). Full defintions available from the survey questionnaires on DataInfo+'],
       [18,
        'Research intended to benefit the sectors of Energy, Manufacturing, Construction, Transport, Information and communication services, or Commercial services and tourism. Full defintions available from the survey questionnaires on DataInfo+'],
       [19,
        'Research intended to benefit the sectors of Health, Education and training, Law, politics, community services or Cultural understanding. Full defintions available from the survey questionnaires on DataInfo+'],
       [20,
        'Research intended to benefit the sectors of Econmic frameworks, Environment, Defence, other or knowledge. Full defintions available from the survey questionnaires on DataInfo+'],
       [21, 'Includes New Zealand local government agencies.'],
       [22,
        'Basic research is carried out to advance knowledge, without seeking long-term economic or social benefits or making any effort to apply the results to sectors responsible for their application.'],
       [23,
        'Pure basic research is research to pursue new knowledge without any particular application in view. '],
       [24,
        'Targeted basic research is research to produce a broad base of new knowledge likely to underpin solutions to current or future applications. '],
       [25,
        'Applied research is investigation undertaken to acquire new knowledge. It is directed primarily towards a specific practical aim or objective.'],
       [26,
        'Experimental research is systematic work undertaken using existing knowledge for the purpose of creating new or improved materials, products, and/or services.'],
       [27,
        'Businesses were asked to indicate one main reason for carrying out or funding R&D. However, some businesses indicated more than one reason. Therefore some percentages may sum to more than 100%. Percentages are of total businesses in each industry group carrying out R&D.'],
       [28,
        'Some categories or groups may not equal the total, as some units can not be imputed or corrected, due to lack of appropriate information.'],
       [29, 'Excludes licensing of intellectual property.'],
       [30, 'Excludes subsidaries.']], dtype=object)

### Sort in ascending order

In [24]:
csv_1.sort_index(axis = 0, ascending = False)

# Note : axis =0 means the row and axis = 1 means according to column

    Number                                           Footnote
29      30                              Excludes subsidaries.
28      29       Excludes licensing of intellectual property.
27      28  Some categories or groups may not equal the to...
26      27  Businesses were asked to indicate one main rea...
25      26  Experimental research is systematic work under...
24      25  Applied research is investigation undertaken t...
23      24  Targeted basic research is research to produce...
22      23  Pure basic research is research to pursue new ...
21      22  Basic research is carried out to advance knowl...
20      21    Includes New Zealand local government agencies.
19      20  Research intended to benefit the sectors of Ec...
18      19  Research intended to benefit the sectors of He...
17      18  Research intended to benefit the sectors of En...
16      17  Research intended to benefit the sectors of Pl...
15      16  Includes 'defence' and 'other' research purposes.
14      15  Respondents are asked to allocate to each of t...
13      14  Underlying counts of employees are rounded usi...
12      13  Underlying counts of businesses are random rou...
11      12  Dollar figures exclude GST and are rounded to ...
10      11  Only collected from the the Crown Research Ins...
9       10  Only collected from the  higher education sect...
8        9  Only collected from the government and higher ...
7        8  Only collected from the business sector and hi...
6        7  Only collected from the business sector and go...
5        6  Only collected from the business sector. Not c...
4        5  Based on Rolling Mean employment. See Datainfo...
3        4  Includes a wide range of ANZSIC industry codes...
2        3  Results for this category should be treated wi...
1        2  In 2019 the R&D Survey was conducted only for ...
0        1  Sector and published industry breakdowns accor...

### change the specific data (LOC FUNCTION)

In [26]:
csv_1.loc[0,"Footnote"] = "Sudeep "
csv_1

    Number                                           Footnote
0        1                                            Sudeep
1        2  In 2019 the R&D Survey was conducted only for ...
2        3  Results for this category should be treated wi...
3        4  Includes a wide range of ANZSIC industry codes...
4        5  Based on Rolling Mean employment. See Datainfo...
5        6  Only collected from the business sector. Not c...
6        7  Only collected from the business sector and go...
7        8  Only collected from the business sector and hi...
8        9  Only collected from the government and higher ...
9       10  Only collected from the  higher education sect...
10      11  Only collected from the the Crown Research Ins...
11      12  Dollar figures exclude GST and are rounded to ...
12      13  Underlying counts of businesses are random rou...
13      14  Underlying counts of employees are rounded usi...
14      15  Respondents are asked to allocate to each of t...
15      16  Includes 'defence' and 'other' research purposes.
16      17  Research intended to benefit the sectors of Pl...
17      18  Research intended to benefit the sectors of En...
18      19  Research intended to benefit the sectors of He...
19      20  Research intended to benefit the sectors of Ec...
20      21    Includes New Zealand local government agencies.
21      22  Basic research is carried out to advance knowl...
22      23  Pure basic research is research to pursue new ...
23      24  Targeted basic research is research to produce...
24      25  Applied research is investigation undertaken t...
25      26  Experimental research is systematic work under...
26      27  Businesses were asked to indicate one main rea...
27      28  Some categories or groups may not equal the to...
28      29       Excludes licensing of intellectual property.
29      30                              Excludes subsidaries.

In [29]:
csv_1.loc[[0,1],["Footnote"]]    

# this displays the specific data of certain row and column

                                            Footnote
0                                            Sudeep
1  In 2019 the R&D Survey was conducted only for ...

In [30]:
csv_1.loc[[0,1],:]

   Number                                           Footnote
0       1                                            Sudeep
1       2  In 2019 the R&D Survey was conducted only for ...

In [31]:
csv_1.loc[:,["Footnote"]]

                                             Footnote
0                                             Sudeep
1   In 2019 the R&D Survey was conducted only for ...
2   Results for this category should be treated wi...
3   Includes a wide range of ANZSIC industry codes...
4   Based on Rolling Mean employment. See Datainfo...
5   Only collected from the business sector. Not c...
6   Only collected from the business sector and go...
7   Only collected from the business sector and hi...
8   Only collected from the government and higher ...
9   Only collected from the  higher education sect...
10  Only collected from the the Crown Research Ins...
11  Dollar figures exclude GST and are rounded to ...
12  Underlying counts of businesses are random rou...
13  Underlying counts of employees are rounded usi...
14  Respondents are asked to allocate to each of t...
15  Includes 'defence' and 'other' research purposes.
16  Research intended to benefit the sectors of Pl...
17  Research intended to benefit the sectors of En...
18  Research intended to benefit the sectors of He...
19  Research intended to benefit the sectors of Ec...
20    Includes New Zealand local government agencies.
21  Basic research is carried out to advance knowl...
22  Pure basic research is research to pursue new ...
23  Targeted basic research is research to produce...
24  Applied research is investigation undertaken t...
25  Experimental research is systematic work under...
26  Businesses were asked to indicate one main rea...
27  Some categories or groups may not equal the to...
28       Excludes licensing of intellectual property.
29                              Excludes subsidaries.

## iloc function

In [32]:
csv_1.iloc[0,1]    # displays data directly

'Sudeep '

#  drop() function ---- removes the specific column or row

In [34]:
csv_1.drop("Footnote" ,axis=1)

    Number
0        1
1        2
2        3
3        4
4        5
5        6
6        7
7        8
8        9
9       10
10      11
11      12
12      13
13      14
14      15
15      16
16      17
17      18
18      19
19      20
20      21
21      22
22      23
23      24
24      25
25      26
26      27
27      28
28      29
29      30

In [35]:
# use of drop function in row

In [36]:
csv_1.drop(1, axis=0)

    Number                                           Footnote
0        1                                            Sudeep
2        3  Results for this category should be treated wi...
3        4  Includes a wide range of ANZSIC industry codes...
4        5  Based on Rolling Mean employment. See Datainfo...
5        6  Only collected from the business sector. Not c...
6        7  Only collected from the business sector and go...
7        8  Only collected from the business sector and hi...
8        9  Only collected from the government and higher ...
9       10  Only collected from the  higher education sect...
10      11  Only collected from the the Crown Research Ins...
11      12  Dollar figures exclude GST and are rounded to ...
12      13  Underlying counts of businesses are random rou...
13      14  Underlying counts of employees are rounded usi...
14      15  Respondents are asked to allocate to each of t...
15      16  Includes 'defence' and 'other' research purposes.
16      17  Research intended to benefit the sectors of Pl...
17      18  Research intended to benefit the sectors of En...
18      19  Research intended to benefit the sectors of He...
19      20  Research intended to benefit the sectors of Ec...
20      21    Includes New Zealand local government agencies.
21      22  Basic research is carried out to advance knowl...
22      23  Pure basic research is research to pursue new ...
23      24  Targeted basic research is research to produce...
24      25  Applied research is investigation undertaken t...
25      26  Experimental research is systematic work under...
26      27  Businesses were asked to indicate one main rea...
27      28  Some categories or groups may not equal the to...
28      29       Excludes licensing of intellectual property.
29      30                              Excludes subsidaries.